FROM richab123/app_server:0.0.2
COPY standalone-sip.xml /b2bua/restcomm-sip-servlets-3.2.0-89-wildfly-10.0.0.Final/standalone/configuration/
COPY mss-sip-stack.properties /b2bua/restcomm-sip-servlets-3.2.0-89-wildfly-10.0.0.Final/standalone/configuration/
