apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: appserver
    spec:
      hostname: appserver
      containers:
      - image: "khankamranali/restcommappserver"
        imagePullPolicy: Always
        name: appserver
        ports:
        - containerPort: 2727
        - containerPort: 5080
        - containerPort: 5081
        - containerPort: 5082
        - containerPort: 5083
        - containerPort: 5084
        - containerPort: 9090
        - containerPort: 9990
        env:
        - name: DOCKER_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["/bin/bash","-c",'cd /b2bua/restcomm-sip-servlets-3.2.0-89-wildfly-10.0.0.Final/bin && sed -i "s/DOCKER_HOST_IP/$DOCKER_HOST_IP/g" /b2bua/restcomm-sip-servlets-3.2.0-89-wildfly-10.0.0.Final/standalone/configuration/standalone-sip.xml && ./standalone.sh -Dzookeeper.conf=kafka:2181 -Dkafka.conf=kafka:9092 -Djboss.bind.address.unsecure=${DOCKER_HOST_IP} -Djboss.bind.address=${DOCKER_HOST_IP} -Djboss.bind.address.management=${DOCKER_HOST_IP} -Djboss.bind.address.sip=${DOCKER_HOST_IP} -Djboss.http.port=9090 -c standalone-sip.xml']
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: appserver
spec:
  type: ClusterIP
  ports:
  - name: "2727"
    port: 2727
  - name: "5080"
    port: 5080
  - name: "5081"
    port: 5081
  - name: "5082"
    port: 5082
  - name: "5083"
    port: 5083
  - name: "5084"
    port: 5084
  - name: "9090"
    port: 9090
  - name: "9990"
    port: 9990
  selector:
    service: appserver
